# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestTNCase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestTNCase
  pod "AFNetworking"
  
  pod "YYModel"
  
  pod "YYCache"
  
  pod "TNMediator", :git => "http://gitlab.mrd.sohuno.com/haixuwu/tnmediator.git"


end
