# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NWUITest' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for NWUITest
  pod 'Masonry'
  pod 'DTCoreText'

  target 'NWUITestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NWUITestUITests' do
    # Pods for testing
  end

end
