# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NWModel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NWModel
pod 'SVProgressHUD'
  target 'NWModelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NWModelUITests' do
    # Pods for testing
  end

end
