name: Publish

on:
  create

jobs:
  build:
    name: Setup Cocoapods based on Podfile.lock
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: Example/Podfile.lock
      
      - name: verify-spec
        run: |
          pod --version
          pod lib lint --use-libraries --allow-warnings
          pod spec lint --use-libraries --allow-warnings
