# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Test0929' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test0929
  
  target 'Test0929Tests' do
    inherit! :search_paths
    # Pods for testing
  pod 'Masonry'
  end

  target 'Test0929UITests' do
    # Pods for testing
  end

end
